### ISSUE TITLE
Bright cyan is too bright

### ISSUE THREAD

**Issue by planet36** [srcery-colors/srcery-terminal#108]
When all the colors are viewed together, bright cyan (#53FDE9) has always stood out as being brighter than the others.

| hex | color | CIELAB lightness | Hue |
|-----|-------|------------------|-----|
| #1C1B19 | ![#1C1B19](https://place-hold.it/100x24/1C1B19?text=+) |  9.8 |  40.0 |
| #918175 | ![#918175](https://place-hold.it/100x24/918175?text=+) | 55.1 |  25.7 |
| #EF2F27 | ![#EF2F27](https://place-hold.it/100x24/EF2F27?text=+) | 52.4 |   2.4 |
| #F75341 | ![#F75341](https://place-hold.it/100x24/F75341?text=+) | 58.4 |   5.9 |
| #519F50 | ![#519F50](https://place-hold.it/100x24/519F50?text=+) | 59.1 | 119.2 |
| #98BC37 | ![#98BC37](https://place-hold.it/100x24/98BC37?text=+) | 71.5 |  76.2 |
| #FBB829 | ![#FBB829](https://place-hold.it/100x24/FBB829?text=+) | 79.0 |  40.9 |
| #FED06E | ![#FED06E](https://place-hold.it/100x24/FED06E?text=+) | 85.7 |  40.8 |
| #2C78BF | ![#2C78BF](https://place-hold.it/100x24/2C78BF?text=+) | 49.2 | 209.0 |
| #68A8E4 | ![#68A8E4](https://place-hold.it/100x24/68A8E4?text=+) | 66.9 | 209.0 |
| #E02C6D | ![#E02C6D](https://place-hold.it/100x24/E02C6D?text=+) | 50.4 | 338.3 |
| #FF5C8F | ![#FF5C8F](https://place-hold.it/100x24/FF5C8F?text=+) | 62.4 | 341.2 |
| #0AAEB3 | ![#0AAEB3](https://place-hold.it/100x24/0AAEB3?text=+) | 64.6 | 181.8 |
| #53FDE9 | ![#53FDE9](https://place-hold.it/100x24/53FDE9?text=+) | 90.8 | 172.9 |
| #BAA67F | ![#BAA67F](https://place-hold.it/100x24/BAA67F?text=+) | 68.9 |  39.7 |
| #FCE8C3 | ![#FCE8C3](https://place-hold.it/100x24/FCE8C3?text=+) | 92.7 |  38.9 |
| #FF5F00 | ![#FF5F00](https://place-hold.it/100x24/FF5F00?text=+) | 61.2 |  22.4 |
| #FF8700 | ![#FF8700](https://place-hold.it/100x24/FF8700?text=+) | 68.5 |  31.8 |

Here are some facts about the current bright cyan
- It has the highest [CIELAB](https://en.wikipedia.org/wiki/CIELAB_color_space) lightness.
- The lightness difference between cyan and bright cyan is greater than any other color (excluding black)
- The hue difference between cyan and bright cyan is one of the highest, after green and orange (excluding black)

Not knowing what process was used to generate the colors, I started with cyan (#0AAEB3) and used [colorizer.org](http://colorizer.org/) to increase the lightness in increments of 1 while not adjusting the hue.  For reference, the first row is cyan, and the last row is the current bright cyan.

| hex | color | CIELAB lightness | Hue |
|-----|-------|------------------|-----|
| #0AAEB3 | ![#0AAEB3](https://place-hold.it/100x24/0AAEB3?text=+) |  64.6 | 181.8 |
| #2EBDC2 | ![#2EBDC2](https://place-hold.it/100x24/2EBDC2?text=+) |  70.1 | 182.0 |
| #32C0C4 | ![#32C0C4](https://place-hold.it/100x24/32C0C4?text=+) |  71.1 | 181.6 |
| #37C2C7 | ![#37C2C7](https://place-hold.it/100x24/37C2C7?text=+) |  71.9 | 182.1 |
| #3BC5CA | ![#3BC5CA](https://place-hold.it/100x24/3BC5CA?text=+) |  73.0 | 182.1 |
| #3FC8CD | ![#3FC8CD](https://place-hold.it/100x24/3FC8CD?text=+) |  74.0 | 182.1 |
| #43CBD0 | ![#43CBD0](https://place-hold.it/100x24/43CBD0?text=+) |  75.1 | 182.1 |
| #46CED2 | ![#46CED2](https://place-hold.it/100x24/46CED2?text=+) |  76.1 | 181.7 |
| #4AD0D5 | ![#4AD0D5](https://place-hold.it/100x24/4AD0D5?text=+) |  76.9 | 182.2 |
| #4ED3D8 | ![#4ED3D8](https://place-hold.it/100x24/4ED3D8?text=+) |  78.0 | 182.2 |
| #51D6DB | ![#51D6DB](https://place-hold.it/100x24/51D6DB?text=+) |  79.0 | 182.2 |
| #55D9DE | ![#55D9DE](https://place-hold.it/100x24/55D9DE?text=+) |  80.1 | 182.2 |
| #58DCE0 | ![#58DCE0](https://place-hold.it/100x24/58DCE0?text=+) |  81.1 | 181.8 |
| #5BDEE3 | ![#5BDEE3](https://place-hold.it/100x24/5BDEE3?text=+) |  81.8 | 182.2 |
| #5FE1E6 | ![#5FE1E6](https://place-hold.it/100x24/5FE1E6?text=+) |  82.9 | 182.2 |
| #62E4E9 | ![#62E4E9](https://place-hold.it/100x24/62E4E9?text=+) |  83.9 | 182.2 |
| #65E7EC | ![#65E7EC](https://place-hold.it/100x24/65E7EC?text=+) |  85.0 | 182.2 |
| #68EAEF | ![#68EAEF](https://place-hold.it/100x24/68EAEF?text=+) |  86.0 | 182.2 |
| #6CEDF1 | ![#6CEDF1](https://place-hold.it/100x24/6CEDF1?text=+) |  87.0 | 181.8 |
| #6FF0F4 | ![#6FF0F4](https://place-hold.it/100x24/6FF0F4?text=+) |  88.1 | 181.8 |
| #72F3F7 | ![#72F3F7](https://place-hold.it/100x24/72F3F7?text=+) |  89.1 | 181.8 |
| #75F6FA | ![#75F6FA](https://place-hold.it/100x24/75F6FA?text=+) |  90.1 | 181.8 |
| #53FDE9 | ![#53FDE9](https://place-hold.it/100x24/53FDE9?text=+) |  90.8 | 172.9 |

I think the bright cyan colors with a lightness in the low 80s are an improvement.

**Comment by roosta** [comment]
I tend to agree, thanks for this nice breakdown! I'll look into changing it after this weekend or during if I have time.

**Comment by roosta** [comment]
I was thinking the new cyans lacks a bit of luster that the original has. When I made the light colors I tried differentiate the light dark variants with a bit of a hue change. So I have a suggestion: I started with the original light and lowered the lightness down to 82, instead of basing it of the dark variant.
| HEX     | color                                                      | Lightness | Hue    | desc                 |
|---------|------------------------------------------------------------|-----------|--------|----------------------|
| #1C1B19 | ![bright-cyan](https://place-hold.it/100x24/2BE4D0?text=+) | 82.13     | 173.55 | my suggestion
| #5FE1E6 | ![#5FE1E6](https://place-hold.it/100x24/5FE1E6?text=+)     | 82.9      | 182.2  | closest in the table |

**Comment by planet36** [comment]
I like it.
