### ISSUE TITLE
kitty autocomplete color is unreadably dark

### ISSUE THREAD

**Issue by peschkaj** [srcery-colors/srcery-terminal#14]
The autocomplete color in kitty is all but unreadable, even at very high brightness on my displays. Something with higher contrast would be beneficial for all users of Kitty. 

Which color is this in the general kitty color scheme?

![Selection-2019-05-30-002](https://user-images.githubusercontent.com/71570/58651413-1ccf6480-82c6-11e9-8266-7f2ce3ee4d66.png)

**Comment by roosta** [comment]
Yeah, I've noticed the same issue with comments in terminal. It uses bright black as the color, I don't know how to fix this save for changing the `bright-black` color to something lighter, more in line with how `white` looks now. In vim it uses `white` as the comment color.

It looks like srcery needs a few palette tweaks, I'll try to make some updates over the weekend, stay tuned.

**Comment by peschkaj** [comment]
For what it's worth, I found `#807d74` to be an acceptable color for `bright-black`. There's probably a better choice that fits in more with the theme, but it does work for the moment.

**Comment by roosta** [comment]
Sorry about the delay on this, I'll get around to it soon. Been busy. Glad you found something that works temporarily.

**Comment by MindTooth** [comment]
I’ll take a look tomorrow.  But I’ve not noticed this to be an issue yet, or at least not been put off by it.

**Comment by MindTooth** [comment]
What shell are you using?

Changing `color8` resulted in changes in more than one place, and that is not suitable.

**Comment by peschkaj** [comment]
I'm using ZSH with purepower (which itself uses powerlevel10k). My current color config from kitty is:

```
# Main Colors {{{

# Black
color0               #1C1B19
color8               #807d74

# Red
color1               #EF2F27
color9               #F75341

# Green
color2               #519F50
color10              #98BC37

# Yellow
color3               #FBB829
color11              #FED06E

# Blue
color4               #2C78BF
color12              #68A8E4

# Magenta
color5               #E02C6D
color13              #FF5C8F

# Cyan
color6               #0AAEB3
color14              #53FDE9

# White
color7               #918175
color15              #FCE8C3

# }}}
```

In the effort of helping you duplicate this (if needed), you can find my ZSH config files at the following locations:
* [purepower](https://github.com/peschkaj/dotfiles/blob/master/zsh/purepower)
* [.zshrc.local](https://github.com/peschkaj/dotfiles/blob/master/zsh/.zshrc.linux.local)
* [.zshenv](https://github.com/peschkaj/dotfiles/blob/master/zsh/.zshenv)

I use a fork of James Off's ZSH config that you can find [over here](https://github.com/peschkaj/zsh)

**Comment by MindTooth** [comment]
I'm not sure how this is easily fixed.  As changing the colors for kitty affects the whole system.  I suspect that the only option if for you to change the colors in ZSH, and make it only affect it.

Tested setting the color you suggested, but then I had the recurring issue of other apps being affected.

**Comment by peschkaj** [comment]
Thanks for looking into this. My terminal is largely just a terminal for running commands, so this one change works for me but I understand that it breaks things for others. 

I'll look into changing the color just for ZSH, too, just in case I use more command line apps in the future. Thanks for that hint!

**Comment by MindTooth** [comment]
I recommend Vim. 😉 

Okay with you that I close the issue?

**Comment by peschkaj** [comment]
I shall close this. Again: thanks for taking the time to look into this.

**Comment by roosta** [comment]
This issue should now be properly resolved
