### ISSUE TITLE
Xresources doesn't have orange, hard black and grays

### ISSUE THREAD

**Issue by anarcat** [srcery-colors/srcery-terminal#161]
I found myself converting my i3 config to use colors from my .Xresources (https://i3wm.org/docs/userguide.html#xresources) to avoid copying stuff all over the place, and noticed that the follow colors are missing from the `Xresources` file:

```
set $orange #D75F00
set $bright_orange #FF8700

set $xgray1 #262626
set $xgray2 #303030
set $xgray3 #3A3A3A
set $xgray4 #444444
set $xgray5 #4E4E4E

set $hard_black #121212
```

looking at the `.Xresources` file, we see it only defines the "basic" 16 colors supported by every terminal. the README file also says:

> Additionally Srcery uses some [xterm 256 colors](https://en.wikipedia.org/wiki/Xterm#/media/File:Xterm_256color_chart.svg) to pad out the color selection, no extra configuration needed.

... yet it's unclear how that works to me in the first place: is srcery just *assuming* those are the colors used by xterm? shouldn't we provide those colors in the Xresources for other applications to use?

**Comment by roosta** [comment]
Hi @anarcat thanks for opening an issue. The reason those aren't defined is because they are already included in the in the default xterm 256 colorscheme, they are unchanged. The reason for this is for compatibility and to have a bit of a wider color selection. You can just refer to the color you need, you don't need to change it.

**Comment by roosta** [comment]
Everything in this table is just default xterm colors
![image](https://user-images.githubusercontent.com/4509009/178533946-ba5ebed2-6a24-45c4-a52c-3839d49796d3.png)

**Comment by roosta** [comment]
Yeah, I suppose we are assuming that those colors remain unchanged, but when I first made srcery, I didn't want to overcomlicate things by having an install script etc. So I just went for the default colors, with the assumption that they are indeed the default colors.

**Comment by anarcat** [comment]
> For reference heres my i3 config

those are strangely different from the one in https://github.com/srcery-colors/srcery-gui/blob/master/i3wm/i3-config and not just because it uses `set_from_resources`, the actual colors are different!

for example. you define:

```
set_from_resource $red            i3wm.color1   #FF3128
set_from_resource $bright_red     i3wm.color9   #DA4939
```

... while the latter defines:

```
set $red #EF2F27
set $bright_red #F75341
```

am i missing something?

**Comment by roosta** [comment]
You can still use xresources as your default, and not having to redefine anything, like I do (or at least I thought I did) The colors are likely different because I maintain a separate config from the one tracked on gui, and I guess I should look into updating the palette :)

**Comment by roosta** [comment]
Setting the colors above 16 in xresources in non-trivial IIRC, and requires more setup than its worth. It's a pretty safe assumption that those colors are the ones defined in https://en.wikipedia.org/wiki/Xterm#/media/File:Xterm_256color_chart.svg and remain unchanged. 
If that isn't the case, and those colors are changed, then that is a config issue, not really something I can address.
