### ISSUE TITLE
Look over `srcery-extra`, and see what needs to be split.

### ISSUE THREAD

**Issue by MindTooth** [srcery-colors/srcery-terminal#7]
Review the whole structure to see what warrants a split from the extras repo.

Set some requirements to follow.

**Comment by roosta** [comment]
I think the terminal configs are a strong contender for splitting out. What about maybe a `srcery-shell` and a `srcery-gui` for the rest?

**Comment by MindTooth** [comment]
Sure.  Works great.  I'll look into using the same method if splitting the code out, but retaining history.

**Comment by roosta** [comment]
That'd be sweet. Let me know if you need more permissions set.

**Comment by roosta** [comment]
I ended up moving what I could while preserving history to:
https://github.com/srcery-colors/srcery-gui
https://github.com/srcery-colors/srcery-web
https://github.com/srcery-colors/srcery-shell
And lastly renamed this repository to `srcery-terminal` as it was the only way to preserve the entire history of the terminal configs.

**Comment by MindTooth** [comment]
Nice 👍
