### ISSUE TITLE
Consistent cursor color

### ISSUE THREAD

**Issue by planet36** [srcery-colors/srcery-terminal#83]
In the Srcery color scheme, which color should be used for the cursor?

These templates use **color 3** (yellow)
* blink.dot
* kitty.dot
* pantheon.dot
* termite.dot
* tilix.dot
* windows_terminal.dot
* xresources.dot

But these templates use the **foreground** color
* chrome-secure-shell.dot
* iterm.dot
* mintty.dot
* terminal-app.dot
* terminator.dot
* xfce.dot

**Comment by roosta** [comment]
It's supposed to be yellow, I'll update the templates. Thanks for reporting

**Comment by roosta** [comment]
Might be an issue with st terminal, was unable to test properly. Set the color to yellow in any case but if anyone has issues let me know.

**Comment by planet36** [comment]
I can fix the st config later.
