### ISSUE TITLE
Output for Terminal.app is broken

### ISSUE THREAD

**Issue by hotoku** [srcery-colors/srcery-terminal#86]
https://github.com/srcery-colors/srcery-terminal/commit/da6f2203ffeb35d879a7aa34948d1306a774e53c#diff-2abd0fba69ef97aa38c3ab4c6e0026525e6d9377dfbab12ed82db4907f95865b

This commit breaks `/terminal_app/srcery_terminal_app.terminal`.

**Comment by roosta** [comment]
Thank you for reporting!

**Comment by hotoku** [comment]
Thank you for quick response 👍
