### ISSUE TITLE
Convert any images to srcery pallete

### ISSUE THREAD

**Issue by RustemB** [srcery-colors/srcery-terminal#95]
Not sure where I should put this request, but can you do stuff like [this](https://github.com/paulopacitti/gruvbox-factory)?

**Comment by MindTooth** [comment]
Hi,

Were not aware of said project.  I'll look into it this weekend.  Posting the request here is just fine. 😉

**Comment by RustemB** [comment]
Any ideas?

**Comment by MindTooth** [comment]
I’ve been busy with school.  In another week or so I’m done.  I’ll look into it then. 👍🏻

**Comment by roosta** [comment]
I've been toying a bit with this, and I did make a thing, but it doesn't really do what you suggest except for some images. I made a program that just goes through each pixel and finds the closes one from the srcery palette. It's slow and not very accurate, I can push to a public repo if anyone wants to try it. Just be ware that your mileage may vary quite a bit.

**Comment by RustemB** [comment]
I want to try it, and maybe I can optimize it

**Comment by roosta** [comment]
Here you go, it's not much but its a start. 

https://github.com/srcery-colors/srcery-convert

Lets move further discussions there, closing this
